### ISSUE TITLE
Non-conformable arguments in estimate function

### ISSUE THREAD

**Issue by crystalnet** [StatisticalReinforcementLearningLab/HeartstepsV1Code#11]
Hey,

I tried to use your code for the data analysis of my micro-randomized trial.
The fitting works just fine, but the estimation yields an error.

This is my code (with sample data, no real data yet):
```
mydata <- data.frame(
    intercept = 1,
    comment_count = rpois(500, 3),
    has_conflicts = sample(0:1, 500, replace = TRUE),
    group = sample(0:10, 500, replace = TRUE),
    base_repo_id = sample(1:11, 500, replace = TRUE)
) 


fit_model1 <- geese.glm(x = as.matrix(mydata[, c("intercept", "comment_count")]),
                        y = mydata$base_repo_id, w = mydata$has_conflicts, id = as.factor(mydata$group),
                        family = gaussian(), corstr = "independence")
estimate(fit_model1)
```

This is the error stacktrace:
```
Error in t(D) %*% V : non-conformable arguments 

Stacktrace:
7.
g(DD, V, r, X, k) at xgeepack.R#150
6.
(function (D, DD, V, r, X, k) 
g(DD, V, r, X, k) - t(D) %*% V %*% D)(D = dots[[1L]][[1L]], DD = dots[[2L]][[1L]], 
    V = dots[[3L]][[1L]], r = dots[[4L]][[1L]], X = dots[[5L]][[1L]], 
    k = dots[[6L]][[1L]]) 
5.
mapply(function(D, DD, V, r, X, k) g(DD, V, r, X, k) - t(D) %*% 
    V %*% D, D = split.data.frame(model.matrix(x) * dot.mu(x), 
    x$id), DD = split.data.frame(model.matrix(x) * dot.mu(x, 
    2), x$id), V = wcovinv, r = split(x$y - x$fitted.values,  ... at xgeepack.R#150
4.
bread.geeglm(x, wcovinv = w) at xgeepack.R#371
3.
vcov.geeglm(x, small = small, ...) 
2.
vcov(x, small = small, ...) at xgeepack.R#412
1.
estimate(fit_model1) 
```

Here is a screenshot of my ```fit_model1```:
![image](https://user-images.githubusercontent.com/16166933/97784225-49636c00-1b9d-11eb-91e6-96d110e7bbf4.png)

I can't really make any sense of this, but the error seems to lie in the ```xgeepack.R``` file in the ```bread.geeglm()``` function.

I would greatly appreciate your help!
Thanks in advance.

EDIT:
I suspected that a new geepack version introduced the error. However, downgrading to ```geepack v1.2.1``` (release of 2016, next version is from December 2019) did not fix the error.

**Comment by aboruvka** [comment]
You need to use `set.seed()` in order to make this error reproducible. Most of the time you will get an error, though, because randomly generating the data in this naive way won't guarantee that the data follows the longitudinal structure needed (e.g. equal number of observations/timepoints per subject). I would have a look at the examples over at [this repo](https://github.com/dalmiral/mHealthModeration) to see the structure needed. I also would avoid using `geese.glm()` directly as it doesn't provide a user-friendly interface for specifying models.
